on:
  push:
    branches:
    - main
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3
      - name: print files
        run: ls -al
    
    
